# Tennis Analytics System Configuration

# Model Paths
models:
  yolo_player: "models/playersnball4.pt"  # Your custom YOLOv8 model for players and ball
  yolo_pose: "models/yolov8n-pose.pt"  # Pose estimation model
  tracknet: "pretrained_ball_detection.pt"  # Ball tracking model (trained)
  yolo_ball: "models/playersnball4.pt"  # YOLO model for ball detection
  court_detector: "model_tennis_court_det.pt"  # Court detection model
  bounce_detector: "models/bounce_detector.cbm"  # Bounce detection model
  rfdetr_model: "models/playersnball5.pt"  # RF-DETR enhanced model for players and ball

# Data Paths
data:
  raw_videos: "data/raw_videos/"
  processed_frames: "data/processed_frames/"
  annotations: "data/annotations/"
  output: "data/output/"

# YOLOv8 Player Detection Settings
yolo_player:
  conf_threshold: 0.5
  iou_threshold: 0.45
  max_det: 10

# YOLO Ball Detection Settings
yolo_ball:
  conf_threshold: 0.1
  iou_threshold: 0.45
  max_det: 10

# Ball Tracking Settings
ball_tracking:
  max_velocity: 200  # Maximum expected ball velocity in pixels per frame
  min_confidence: 0.3  # Minimum confidence for ball detection
  smoothing_factor: 0.7  # Smoothing factor for ball position
  prediction_frames: 3  # Number of frames to predict ahead

# RF-DETR Enhanced Detection Settings
rfdetr:
  player_conf_threshold: 0.3  # Confidence threshold for player detection
  ball_conf_threshold: 0.2    # Confidence threshold for ball detection
  max_players: 2              # Maximum number of players to detect
  max_balls: 1                # Maximum number of balls to detect

# YOLOv8 Pose Estimation Settings
yolo_pose:
  conf_threshold: 0.3
  iou_threshold: 0.45
  max_det: 4  # Max 4 players on court
  keypoints: 17  # COCO keypoints

# TrackNet Ball Tracking Settings (PyTorch)
tracknet:
  input_height: 360
  input_width: 640
  conf_threshold: 0.1  # Lower threshold for TrackNet
  max_dist: 100
  max_gap: 4
  min_track_length: 5

# Court Detection Settings
court_detection:
  input_width: 640
  input_height: 360
  low_threshold: 170
  min_radius: 10
  max_radius: 25
  use_refine_kps: true
  use_homography: true

# Video Processing
video:
  fps: 30
  frame_skip: 1  # Process every nth frame
  resize_width: 1920
  resize_height: 1080

# Analysis Settings
analysis:
  swing_detection:
    min_confidence: 0.7
    keypoint_threshold: 0.3
  ball_tracking:
    min_trajectory_length: 10
    max_gap_frames: 5
  court_detection:
    enabled: true
    homography_method: "RANSAC"

# Output Settings
output:
  save_annotated_videos: true
  save_pose_data: true
  save_ball_trajectories: true
  save_analytics: true
  format: "json"

# Pose estimation model
pose_model_path: "models/yolov8x-pose.pt"
