# Tennis Analytics System Configuration

# Model Paths
models:
  yolo_player: "playersnball4.pt"  # Your custom YOLOv8 model for players and ball
  yolo_pose: "models/yolov8n-pose.pt"  # Pose estimation model
  tracknet: "exps/default/model_last.pt"  # Ball tracking model (trained)

# Data Paths
data:
  raw_videos: "data/raw_videos/"
  processed_frames: "data/processed_frames/"
  annotations: "data/annotations/"
  output: "data/output/"

# YOLOv8 Player Detection Settings
yolo_player:
  conf_threshold: 0.5
  iou_threshold: 0.45
  max_det: 10

# YOLOv11 Pose Estimation Settings
yolo_pose:
  conf_threshold: 0.3
  iou_threshold: 0.45
  max_det: 4  # Max 4 players on court
  keypoints: 17  # COCO keypoints

# TrackNet Ball Tracking Settings (PyTorch)
tracknet:
  input_height: 360
  input_width: 640
  conf_threshold: 0.5
  max_dist: 100
  max_gap: 4
  min_track_length: 5

# Video Processing
video:
  fps: 30
  frame_skip: 1  # Process every nth frame
  resize_width: 1920
  resize_height: 1080

# Analysis Settings
analysis:
  swing_detection:
    min_confidence: 0.7
    keypoint_threshold: 0.3
  ball_tracking:
    min_trajectory_length: 10
    max_gap_frames: 5
  court_detection:
    enabled: true
    homography_method: "RANSAC"

# Output Settings
output:
  save_annotated_videos: true
  save_pose_data: true
  save_ball_trajectories: true
  save_analytics: true
  format: "json"
